# Origin Input
Vehicle_Signal_To_Tsm:
  BCS_VehicleStandStillSt: 1
  BCM_LeftTurnLampSt: 0
  BCM_RightTurnLampSt: 0
  BCM_HazardLampSt: 0
  EBB_BrkPedalAppliedSt: 1
  EBB_BrkPedalApplied: 1
  HOD_TouchZone1: 0
  HOD_TouchZone2: 1
  HOD_TouchZone3: 0
  HOD_CalibrationSt: 0
  HOD_FaultStatus: 0
  EPS_StrngWhlTorqVD: 1
  EPS_StrngWhlTorq: -1.6
  EMS_GasPedalActPstforMRRVD: 1
  EMS_GasPedalActPstforMRR: 19.0

Soc_Info:
  NDA_Function_State: 0
  ICA_Function_State: 0

From_Diag:
  com_fault_with_adc: 0
  is_support_lane_stop: 1
  is_support_emergency_stop: 0
  
From_Planlite:
  planningLite_control_state: 0

  
