# Origin Input
Vehicle_Signal_To_Tsm:
  BCS_VehicleStandStillSt: 0
  BCM_HazardLampSt: 0
  EBB_BrkPedalAppliedSt: 1
  EBB_BrkPedalApplied: 0
  HOD_TouchZone1: 0
  HOD_TouchZone2: 0
  HOD_TouchZone3: 0
  HOD_CalibrationSt: 0
  HOD_FaultStatus: 0
  EPS_StrngWhlTorqVD: 1
  EPS_StrngWhlTorq: -1.1
  EMS_GasPedalActPstforMRRVD: 1
  EMS_GasPedalActPstforMRR: 19.0
  BCS_VehSpd: 31.0
  BCS_YawRate: 19.0
  BCS_ActVehLaltrlAccel: 1.0
  BCS_ActVehLongAccel: 6.0
  EPS_SteeringAngleSpd: 20.0
  VCU_CrntGearLvlVD: 1
  VCU_CrntGearLvl: 1
  VCU_VehRdySt: 1
  EPB_SwitchStVD: 1
  EPB_SwitchSt: 1
  EPB_SysSt: 0
  BCM_KeySt: 2
  BCS_HDCCtrlSt: 4
  BCS_VDCActiveS: 0
  BCS_ABSActiveSt: 0
  BCS_TCSActiveSt: 0
  BCS_EBDActiveSt: 0
  BCS_CDDAvailable: 1

Soc_Info:
  NDA_Function_State: 14
  ICA_Function_State: 0
  Vehicle_Posture_St: 1
  Vehicle_Position_St: 1

From_CtrlArb:
  AS_lng_ctrl_st: 0
  AS_lat_ctrl_st: 0

From_Diag:
  mcu_mrm_fault_level: 0
  is_support_lane_stop: 1
  is_support_emergency_stop: 1
  
From_Planlite:
  planningLite_control_state: 0

  
